/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.UnidadeController;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Unidade;
import model.UnidadeTableModel;
import util.GerarCodigoAleatorio;
import util.StringUtils;

/**
 *
 * @author edson
 */
public class UnidadeDialog extends javax.swing.JDialog {

    private UnidadeController unidadeController;
    private List<Unidade> unidades;
    private int idUnidade = 0;

    /**
     * Creates new form UnidadeDialog
     */
    public UnidadeDialog(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        unidadeController = new UnidadeController();
        carregaTabela();
        txtSiglaUnidade.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        spPrincipal = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblSiglaUnidade = new javax.swing.JLabel();
        txtSiglaUnidade = new javax.swing.JTextField();
        lblDescricaoUnidade = new javax.swing.JLabel();
        txtDescricaoUnidade = new javax.swing.JTextField();
        btnSalvarUnidade = new javax.swing.JButton();
        ckAtivaUnidade = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        lblIdUnidade = new javax.swing.JLabel();
        txtIdUnidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UNIDADE");

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SIGLA", "DESCRIÇÃO", "ATIVO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        spPrincipal.setViewportView(jTable1);

        lblSiglaUnidade.setText("SIGLA");

        lblDescricaoUnidade.setText("DESCRIÇÃO DE UNIDADE");

        btnSalvarUnidade.setBackground(new java.awt.Color(0, 255, 0));
        btnSalvarUnidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-salvar-22.png"))); // NOI18N
        btnSalvarUnidade.setText("SALVAR");
        btnSalvarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUnidadeActionPerformed(evt);
            }
        });

        ckAtivaUnidade.setSelected(true);
        ckAtivaUnidade.setText("ATIVO");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-vassoura-22.png"))); // NOI18N
        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblIdUnidade.setText("ID");

        txtIdUnidade.setText("0");
        txtIdUnidade.setEnabled(false);

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricaoUnidade)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckAtivaUnidade)
                            .addComponent(lblDescricaoUnidade)
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdUnidade)
                                    .addComponent(txtIdUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lblSiglaUnidade))
                                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSiglaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnPrincipalLayout.createSequentialGroup()
                                .addComponent(btnSalvarUnidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalLayout.createSequentialGroup()
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdUnidade)
                            .addComponent(lblSiglaUnidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSiglaUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricaoUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckAtivaUnidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarUnidade)
                            .addComponent(jButton1))
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(spPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUnidadeActionPerformed
        if (idUnidade != 0) {
            Object[] options = {"Confirmar", "Cancelar"};
            if (JOptionPane.showOptionDialog(null, "Deseja realmente alterar #" + idUnidade,
                    "Aviso", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, options, options[1]) == 0) {
                // Gerar um código aleatório
                String codigoDeConfirmacaoAleatorio = GerarCodigoAleatorio.gerarCodigoAleatorio();
                // Exibir um JOptionPane para obter o código
                String codigoDeConfirmacao = JOptionPane.showInputDialog(null,
                        "Insira o código de 4 dígitos: " + codigoDeConfirmacaoAleatorio,
                        "Confirmação", JOptionPane.WARNING_MESSAGE);
                // Comparar os códigos
                if (codigoDeConfirmacao != null && codigoDeConfirmacao.length() == 4
                        && codigoDeConfirmacao.equals(codigoDeConfirmacaoAleatorio)) {
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Código incorreto ou invalido.");
                }

            }
        } else {
            salvar();
        }


    }//GEN-LAST:event_btnSalvarUnidadeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) { // Verifica se foi um duplo clique
            Object[] options = {"Confirmar", "Cancelar"};
            if (JOptionPane.showOptionDialog(null, "Clique Confirmar para alterar",
                    "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) == 0) {
                int rowIndex = jTable1.getSelectedRow(); // Obtenha a linha selecionada na tabela
                idUnidade = (int) jTable1.getValueAt(rowIndex, 0); // Obtenha o ID da primeira coluna (coluna 0)

                Unidade unidade = unidadeController.obterUnidadePorId(idUnidade);

                idUnidade = unidade.getId();
                txtIdUnidade.setText("" + unidade.getId());
                txtSiglaUnidade.setText(unidade.getSigla());
                txtSiglaUnidade.requestFocus();
                txtDescricaoUnidade.setText(unidade.getDescricao());
                ckAtivaUnidade.setSelected(unidade.isAtivo());
                btnSalvarUnidade.setText("ALTERAR");
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limparCampos();

        carregaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if (evt.getKeyCode() == evt.VK_DELETE) {
            int rowIndex = jTable1.getSelectedRow(); // Obtenha a linha selecionada na tabela
            idUnidade = (int) jTable1.getValueAt(rowIndex, 0); // Obtenha o ID da primeira coluna (coluna 0)

            Object[] options = {"Confirmar", "Cancelar"};
            if (JOptionPane.showOptionDialog(null, "Clique Confirmar para continuar",
                    "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[1]) == 0) {

                // Gerar um código aleatório
                String codigoDeConfirmacaoAleatorio = GerarCodigoAleatorio.gerarCodigoAleatorio();
                // Exibir um JOptionPane para obter o código
                String codigoDeConfirmacao = JOptionPane.showInputDialog(null,
                        "Insira o código de 4 dígitos: " + codigoDeConfirmacaoAleatorio,
                        "Confirmação", JOptionPane.WARNING_MESSAGE);
                // Comparar os códigos
                if (codigoDeConfirmacao != null && codigoDeConfirmacao.length() == 4
                        && codigoDeConfirmacao.equals(codigoDeConfirmacaoAleatorio)) {
                    unidadeController.marcarUnidadeComoDeletada(idUnidade);
                    unidadeController.carregarUnidadeSeVazia();
                    carregaTabela();
                } else {
                    JOptionPane.showMessageDialog(null, "Código incorreto ou invalido.");
                }

            }
            System.out.println("delete - " + idUnidade);
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnidadeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnidadeDialog dialog = null;
                try {
                    dialog = new UnidadeDialog(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(UnidadeDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarUnidade;
    private javax.swing.JCheckBox ckAtivaUnidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDescricaoUnidade;
    private javax.swing.JLabel lblIdUnidade;
    private javax.swing.JLabel lblSiglaUnidade;
    private javax.swing.JPanel pnPrincipal;
    private javax.swing.JScrollPane spPrincipal;
    private javax.swing.JTextField txtDescricaoUnidade;
    private javax.swing.JTextField txtIdUnidade;
    private javax.swing.JTextField txtSiglaUnidade;
    // End of variables declaration//GEN-END:variables

    public void carregaTabela() {
        List<Unidade> listaDeUnidades = unidadeController.listarUnidades();
        UnidadeTableModel tableModel = new UnidadeTableModel(listaDeUnidades); // Substitua "listaDeUnidades" pelos seus dados
        jTable1.setModel(tableModel);
    }

    public void limparCampos() {
        idUnidade = 0;
        txtIdUnidade.setText("0");
        txtSiglaUnidade.setText("");
        txtSiglaUnidade.requestFocus();
        txtDescricaoUnidade.setText("");
        ckAtivaUnidade.setSelected(true);
        btnSalvarUnidade.setText("SALVAR");
    }

    private void salvar() {
        String sigla = txtSiglaUnidade.getText().toUpperCase(),
                descricao = StringUtils.restringirTamanhoString(txtDescricaoUnidade.getText().toUpperCase(), 25);

        if (unidadeController.siglaDescricaoVazias(sigla, descricao)) {
            JOptionPane.showMessageDialog(UnidadeDialog.this,
                    "Verifique campos vazios.", "Avisso",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            if (unidadeController.salvararUnidade(idUnidade, sigla.toUpperCase(),
                    descricao.toUpperCase(),
                    ckAtivaUnidade.isSelected())) {
                limparCampos();
                unidadeController.carregarUnidadeSeVazia();
                carregaTabela();
                JOptionPane.showMessageDialog(UnidadeDialog.this, "Unidade salva com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } else {

                JOptionPane.showMessageDialog(UnidadeDialog.this,
                        "Ocorreu um erro ao salvar a unidade.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
