/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import controller.CFOPController;
import controller.ClienteController;
import controller.NCMController;
import controller.ProdutoController;
import controller.TransacaoController;
import controller.UnidadeController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import view.Login;

public class IniciandoSistema extends javax.swing.JFrame {

    Login login = new Login();

    UnidadeController unidadeController;
    CFOPController cfopController;
    NCMController ncmController;
    ProdutoController produtoController;
    TransacaoController transacaoController;
    ClienteController clienteController;

    public IniciandoSistema() {
        initComponents();
        carrega();
    }

    private void carrega() {
        try {
            unidadeController = new UnidadeController();
            unidadeController.carregarUnidadeSeVazia();

            lblCarregando.setText("Carregando... unidades");

            cfopController = new CFOPController();
            cfopController.carregaCfopSeVazio();

            lblCarregando.setText("Carregando... cfop");

            ncmController = new NCMController();
            ncmController.carregaNcmSeVazio();

            lblCarregando.setText("Carregando... ncm");

            produtoController = new ProdutoController();
            produtoController.carregaProdutosSeVazio();

            lblCarregando.setText("Carregando... produtos");

            clienteController = new ClienteController();
            clienteController.carregaClientesSeVazio();

            lblCarregando.setText("Carregando... clientes");

            transacaoController = new TransacaoController();
            transacaoController.carregaTransacoesSeVazio();

            lblCarregando.setText("Carregando... transações");

        } catch (Exception e) {
            System.out.println("Erro:: " + e);
        }

        Timer timer = new Timer(50, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                login.setVisible(true);
                ((Timer) e.getSource()).stop();
                dispose();

            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCarregando = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblCarregando.setFont(new java.awt.Font("Fira Sans", 1, 18)); // NOI18N
        lblCarregando.setForeground(new java.awt.Color(51, 51, 51));
        lblCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarregando.setText("Carregando...");
        jPanel1.add(lblCarregando, java.awt.BorderLayout.CENTER);

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/storyline-500.jpg"))); // NOI18N
        jPanel1.add(lblImagem, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciandoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciandoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciandoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciandoSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciandoSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarregando;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
